### ISSUE TITLE
Number rounding

### ISSUE THREAD

**Issue by FluxDelta** [dingusdk/haihc-betatest#6]
## Your IHC controller

IHC Visual 3 HW 7.1 - Firmware 3.3.45

## Describe the bug

Rounding of numbers.

Numbers (e.g. temperature, humidity) end up being reported with many digits even though the controller only measures temperature, humidity with a 0.1 precision. It would be nice with a feature that would allow automatic rounding of numbers from sensors.

## Debug log

```text


```

**Comment by duddi** [comment]
You can do that with template,
```
template:
## Stue Temperatur & Fugtighed
  - sensor:
    - name: Temp_stue
      unique_id: Temp_stue
      unit_of_measurement: "°C"
      state: "{{ states('sensor.stue_j_ok_5692180') | round(1)}}"
  - sensor:
    - name: Fugt_stue
      unique_id: Fugt_stue
      unit_of_measurement: "%"
      state: "{{ states('sensor.stue_j_ok_5691943') | round(1)}}"
```
